package com.admin.entity;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.*;

import java.util.UUID;

@DynamoDBTable(tableName = "AdminLogs")
@Setter
@AllArgsConstructor
public class Log {

    private String logId;
    private Long timestamp;
    private String action;
    private String adminId;
    private String details;
    private String userAgent;
    private String approximateLocation;

    public Log() {
        logId = UUID.randomUUID().toString();
        timestamp = System.currentTimeMillis();
    }

    public static class Builder {
        Log log;

        public Builder() {
            log = new Log();
        }

        public Builder withAction(String action) {
            log.setAction(action);
            return this;
        }

        public Builder withAdminId(String adminId) {
            log.setAdminId(adminId);
            return this;
        }

        public Builder withDetails(String details) {
            log.setDetails(details);
            return this;
        }

        public Builder withUserAgent(String userAgent) {
            log.setUserAgent(userAgent);
            return this;
        }

        public Builder withApproximateLocation(String approximateLocation) {
            log.setApproximateLocation(approximateLocation);
            return this;
        }

        public Log build() {
            return log;
        }
    }

    public static Builder builder() {
        return new Builder();
    }

    @DynamoDBHashKey(attributeName = "logId")
    @DynamoDBAutoGeneratedKey
    public String getLogId() {
        return logId;
    }

    @DynamoDBRangeKey(attributeName = "timestamp")
    public Long getTimestamp() {
        return timestamp;
    }

    @DynamoDBAttribute(attributeName = "action")
    public String getAction() {
        return action;
    }

    @DynamoDBAttribute(attributeName = "adminId")
    public String getAdminId() {
        return adminId;
    }

    @DynamoDBAttribute(attributeName = "details")
    public String getDetails() {
        return details;
    }

    @DynamoDBAttribute(attributeName = "userAgent")
    public String getUserAgent() {
        return userAgent;
    }

    @DynamoDBAttribute(attributeName = "approximateLocation")
    public String getApproximateLocation() {
        return approximateLocation;
    }
}