package com.admin.entity;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.Setter;

import java.time.Instant;
import java.util.UUID;

@DynamoDBTable(tableName = "Transactions")
@Setter
public class Transaction {

    private String transactionId = UUID.randomUUID().toString();
    private String createdAt;
    private String actionType;
    private String initiatedBy;
    private String status;
    private String details;
    private String service;
    private String target;

    public Transaction() {
        createdAt = Instant.now().toString();
    }

    public static class Builder {
        Transaction transaction;

        public Builder() {
            transaction = new Transaction();
        }

        public Builder withTarget(String target) {
            transaction.setTarget(target);
            return this;
        }

        public Builder withActionType(String actionType) {
            transaction.setActionType(actionType);
            return this;
        }

        public Builder withInitiatedBy(String initiatedBy) {
            transaction.setInitiatedBy(initiatedBy);
            return this;
        }

        public Builder withStatus(String status) {
            transaction.setStatus(status);
            return this;
        }

        public Builder withDetails(String details) {
            transaction.setDetails(details);
            return this;
        }

        public Builder withService(String service) {
            transaction.setService(service);
            return this;
        }

        public Transaction build() {
            return transaction;
        }
    }

    public static Builder builder() {
        return new Builder();
    }

    @DynamoDBHashKey(attributeName = "transactionId")
    @DynamoDBAutoGeneratedKey
    public String getTransactionId() {
        return transactionId;
    }

    @DynamoDBRangeKey(attributeName = "createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    @DynamoDBAttribute(attributeName = "actionType")
    public String getActionType() {
        return actionType;
    }

    @DynamoDBAttribute(attributeName = "initiatedBy")
    public String getInitiatedBy() {
        return initiatedBy;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute(attributeName = "details")
    public String getDetails() {
        return details;
    }

    @DynamoDBAttribute(attributeName = "service")
    public String getService() {
        return service;
    }

    @DynamoDBAttribute(attributeName = "target")
    public String getTarget() {
        return target;
    }
}

